// examples/vue/src/App.vue
<template>
  <table>
    <thead>
      <th>Id</th>
      <th>Previous Hash</th>
      <th>Height</th>
      <th>Timestamp</th>
      <th>Version</th>
    </thead>
    <tbody>
      <tr v-for="block in blocks" :key="block.id">
        <td>{{block.id}}</td>
        <td>{{block.previousblockhash}}</td>
        <td>{{block.height}}</td>
        <td>{{block.timestamp}}</td>
        <td>{{block.version}}</td>
      </tr>
    </tbody>
  </table>
</template>

<script>
import zoobc from 'zoobc'

export default {
  name: 'app',
  data () {
    return {
      blocks: [],
      error: ''
    }
  },

  created() {
    this.listBlocks()
  },

  methods: {
    listBlocks() {
      zoobc.connection('http://18.139.3.139:7001')
      zoobc.getBlocks(0, 5, 1)
        .then(res => {
          this.blocks = res.blocksList
        })
        .catch(err => {
          this.error = err
        })
      }
  }
}

</script>

<style scoped>
  
</style>

// examples/angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import zoobc from 'zoobc';

@Component({
  selector: 'app-root',
  templateUrl: `./app.component.html`,
  styleUrls: ['./app.component.css']
})

export class AppComponent implements OnInit {
  list = [];
  title = 'angular app';

  ngOnInit(): void {
    this.getBlocks().then(data => {
      this.list = data.blocksList;
    });
  }

  getBlocks() {
    zoobc.connection('http://18.139.3.139:7001');
    const a = zoobc.getBlocks(0, 5, 1);
    return a;
  }
}

<!--The content below is only a placeholder and can be replaced.-->
<html>
<head></head>
<body>
  <table border="1" width="100%">
    <thead>
      <th>Id</th>
      <th>Previous Hash</th>
      <th>Height</th>
      <th>Timestamp</th>
      <th>Version</th>
    </thead>
    <tbody >
      <tr *ngFor="let list of lists">
        <td>{{list.id}}</td>
        <td>{{list.previousblockhash}}</td>
        <td>{{list.height}}</td>
        <td>{{list.timestamp}}</td>
        <td>{{list.version}}</td>
    </tr>
    </tbody>
  </table>
</body>
</html>
