// examples/vue/src/App.vue
<template>
  <table>
    <thead>
      <th>Id</th>
      <th>Previous Hash</th>
      <th>Height</th>
      <th>Timestamp</th>
      <th>Version</th>
    </thead>
    <tbody>
      <tr v-for="block in blocks" :key="block.id">
        <td>{{block.id}}</td>
        <td>{{block.previousblockhash}}</td>
        <td>{{block.height}}</td>
        <td>{{block.timestamp}}</td>
        <td>{{block.version}}</td>
      </tr>
    </tbody>
  </table>
</template>

<script>
import zoobc from 'zoobc'

export default {
  name: 'app',
  data () {
    return {
      blocks: [],
      error: ''
    }
  },

  created() {
    this.listBlocks()
  },

  methods: {
    listBlocks() {
      zoobc.connection('http://18.139.3.139:7001')
      zoobc.getBlocks(0, 5, 1)
        .then(res => {
          this.blocks = res.blocksList
        })
        .catch(err => {
          this.error = err
        })
      }
  }
}

</script>

<style scoped>
  
</style>

// examples/angular1/src/app/app.component.ts
import { Component } from '@angular/core';
import zoobc from 'zoobc';

@Component({
  selector: 'app-root',
  templateUrl: `./app.component.html`,
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  list = this.getBlocks();
  title = 'angular app';

  ngOnInit(): void {
    this.getBlocks();

  }
  getBlocks() {
    zoobc.connection('http://18.139.3.139:7001');
    return zoobc.getBlocks(0, 5, 1);
  }
}

<!--The content below is only a placeholder and can be replaced.-->
<head></head>
<body>
  <table>
    <thead>
      <th>Id</th>
      <th>Previous Hash</th>
      <th>Height</th>
      <th>Timestamp</th>
      <th>Version</th>
    </thead>
    <tbody *ngFor="let data of list; let i = index">
      <td>{{data.id}}</td>
      <td>{{data.previousblockhash}}</td>
      <td>{{data.height}}</td>
      <td>{{data.timestamp}}</td>
      <td>{{data.version}}</td>
    </tbody>
  </table>
</body>>
